### Dependancies used in the app ###
library(shiny)
library(tidyverse)
library(xml2)
library(leaflet)
library(leafem)
library(DT)
library(shinydashboard)
library(rintrojs)
library(shinyBS)
library(plotly)
library(dashboardthemes)
library(emo)
library(viridis)
library(rgdal)
library(raster)
library(rgeos)
library(gstat)
library(data.table)
library(mapview)
library(shiny.i18n)
library(tmap)
library(stars)
library(starsExtra)


# Translation file
i18n <- Translator$new(translation_json_path = "/home/rstudio/app/translation.json")
i18n$set_translation_language("no")